# Generated by Django 4.2.1 on 2024-04-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_token',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='refresh_token',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
