# Generated by Django 5.0.1 on 2024-04-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.TextField(default='what is happening'),
            preserve_default=False,
        ),
    ]
