# Generated by Django 4.2.1 on 2024-04-23 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_user_access_token_alter_user_refresh_token'),
        ('backend', '0002_conversation_name'),
    ]

    operations = [
    ]
