# Generated by Django 5.0.4 on 2024-05-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_accesslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='headers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='message',
            name='is_tabular',
            field=models.BooleanField(default=False),
        ),
    ]
