# Generated by Django 5.0.4 on 2024-05-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_message_headers_message_is_tabular'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tableData',
            field=models.JSONField(default=list),
        ),
    ]
