# Generated by Django 5.0.4 on 2024-05-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_message_tabledata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='answer',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
