# Generated by Django 5.0.4 on 2024-05-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_message_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='headers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='tableData',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
